"""new fields in user model

Revision ID: 344d310334b1
Revises: 497ad683ba38
Create Date: 2021-04-21 04:58:47.854353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344d310334b1'
down_revision = '497ad683ba38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
